# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=100)),
                ('ref', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_id', models.CharField(max_length=15)),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpref.Phenotype')),
            ],
        ),
    ]
