# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpref', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SNP2Ref2Phen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='phenotype',
        ),
        migrations.AddField(
            model_name='snp2ref2phen',
            name='phenotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpref.Phenotype'),
        ),
        migrations.AddField(
            model_name='snp2ref2phen',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpref.Reference'),
        ),
        migrations.AddField(
            model_name='snp2ref2phen',
            name='snp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpref.SNP'),
        ),
    ]
