# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snpref', '0003_auto_20170512_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SNPRefPhen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpref.Phenotype')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpref.Reference')),
            ],
        ),
        migrations.RemoveField(
            model_name='snp',
            name='phenotype',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='ref',
        ),
        migrations.AddField(
            model_name='snprefphen',
            name='snp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpref.SNP'),
        ),
    ]
